### ISSUE TITLE
On builds:create, "path must be a string. received undefined"

### ISSUE THREAD

**Issue by deanpapastrat** [heroku/heroku-builds#45]
On Heroku 6.11.7 (`heroku-cli/6.11.7-4cda136 node-v7.10.0`) with plugins v0.0.16, I'm getting:

```sh
$ heroku builds:create -a <app-name-redacted>
 ▸    Path must be a string. Received undefined
```

Any ideas on how I can solve this? I currently can't deploy to production because of this.

**Comment by dmathieu** [comment]
Could you run the following command:

> HEROKU_DEBUG=1 heroku builds:create -a <app name>

And paste the full output here?

**Comment by deanpapastrat** [comment]
```sh
updating cache for /Users/deanpapastrat/.local/share/heroku/plugins/node_modules/heroku-builds
--> POST /apps/sideqik/sources
--> {}
<-- 201 Created
<-- {"source_blob":{"get_url":"<redacted-url>"}}
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:1146:7)
    at setopts (/Users/deanpapastrat/.local/share/heroku/plugins/node_modules/glob/common.js:97:21)
    at new GlobSync (/Users/deanpapastrat/.local/share/heroku/plugins/node_modules/glob/sync.js:40:3)
    at Function.globSync [as sync] (/Users/deanpapastrat/.local/share/heroku/plugins/node_modules/glob/sync.js:26:10)
    at /Users/deanpapastrat/.local/share/heroku/plugins/node_modules/archiver-utils/file.js:62:17
    at /Users/deanpapastrat/.local/share/heroku/plugins/node_modules/archiver-utils/file.js:30:19
    at Array.forEach (native)
    at processPatterns (/Users/deanpapastrat/.local/share/heroku/plugins/node_modules/archiver-utils/file.js:24:23)
    at Object.file.expand (/Users/deanpapastrat/.local/share/heroku/plugins/node_modules/archiver-utils/file.js:60:17)
Exiting with code: 1
```

**Comment by dmathieu** [comment]
Dean,

This looks like an issue preventing your tar from being generated. Do you have symlinks within your app's code?
Did this work at some point?
Could you try using gnu tar and see if that works?

Finally, at this point, it might be easier if you open a support ticket on help.heroku.com, as we'll then be able to fetch your code and better help you debug this.

Thanks,
Damien

**Comment by dmathieu** [comment]
Closing as stale.
